### ISSUE TITLE
Hwo to install the environment provided?

### ISSUE THREAD

**Issue by sofa-potato** [raminaghods/Multi-agent-active-search#3]
Hwo to install the environment provided?

**Comment by b18arundhati** [comment]
You can follow the steps here to install the conda environment from the provided .yml file.

[https://saturncloud.io/blog/how-to-create-a-conda-environment-based-on-a-yaml-file-a-guide-for-data-scientists/](url)

**Comment by sofa-potato** [comment]
when i create this env, it always makes this:
 
C:\Windows\system32>conda env create -f F:\Project_python\RL\Multi-agent-active-search-master\Multi-agent-active-search-master\MultiAgentEnv.yml
Channels:
 - pytorch
 - conda-forge
 - anaconda
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - zstd==1.3.7=h0b5b093_0
  - zlib==1.2.11=h7b6447c_3
  - zeromq==4.3.1=he6710b0_3
  - yaml==0.1.7=had09818_2
  - xz==5.2.4=h14c3975_4
  - xorg-xproto==7.0.31=h14c3975_1007
  - xorg-xextproto==7.3.0=h14c3975_1002
  - xorg-renderproto==0.11.1=h14c3975_1002
  - xorg-libxrender==0.9.10=h516909a_1002
  - xorg-libxext==1.3.4=h516909a_0
  - xorg-libx11==1.6.9=h516909a_0
  - xorg-libsm==1.2.3=h84519dc_1000
  - xorg-libice==1.0.10=h516909a_0
  - xorg-kbproto==1.0.7=h14c3975_1002
  - x264==1!152.20180806=h14c3975_0
  - wurlitzer==1.0.3=py37_0
  - wrapt==1.11.2=py37h7b6447c_0
  - unixodbc==2.3.7=h14c3975_0
  - torchvision==0.4.2=py37_cu101
  - tk==8.6.8=hbc83047_0
  - tbb==2019.8=hfd86e86_0
  - statsmodels==0.12.1=py37h27cfd23_0
  - sqlite==3.30.1=h7b6447c_0
  - sqlalchemy==1.3.10=py37h7b6447c_0
  - snappy==1.1.7=hbae5bb6_3
  - .......
